name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ghcr.io/JuliaMorokina/top-api/top-api
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          tags: "develop"
